### PR TITLE
feat(events): create visitor on check-in

### LINKED ISSUE #29: feat(guest): support checkin without an existing guest record
In some scenarios, the enterprise will not be using placeos workplace app. Events will be created using the native applications like Outlook or Google Calendar. In this case there is no POST to staff-api when creating an event and so no staff-api event metadata or guests are stored.

We still want to enable the possibility of a visitor-kiosk and perhaps even concierge app in those scenarios, and so the visitor-kiosk would need to allow the visitor to enter their email address and select their event for checkin. Doing so should result in a POST to a [new or updated](https://placeoscalendar.docs.apiary.io/#reference/0/guests) Guest endpoint.

The endpoint should result in staff-api:
- storing the guest's details
  - onsite visit: true
  - checked in: true
  - record the time of the check in (for reporting purposes)
- storing the associated Event metadata (if it doesn't already exist)
- Trigger any relevant Signals (like /staff/guest/checkin)

### PR DESCRIPTION
**Pull request by stakach**
fixes #29

### CODE REVIEW

**Review by tassja — DISMISSED** [review]

**Comment by w-le** [comment]
Using CONCIERGE to CHECK-IN a guest who has never been detected by staff-api before
```
Request URL: https://<placeos dev vm>/api/staff/v1/events/AAkALgAAAAAAHYQDEapmouf3io2444dfo3C-EWg0AHlzu7DNLkUWaRWQA91iWkgAD2pa15wAA/guests/steve@place.tech/checkin?system_id=sys-GAfNtUViWCw&state=true
Request Method: POST

Status Code: 500 Internal Server Error  (empty body)

staff-api error:
level=[E] time=2021-09-01T07:17:27Z program=StaffAPI source=action-controller client_ip=REDACTED request_id=8cd07af7-953b-4d84-b6ae-REDACTED domain=REDACTED tenant_id=3 event=error method=POST path=/api/staff/v1/events/AAkALgAAAAAAHYQDEapmEc2byACqAC-REDACTED/guests/steve@place.tech/checkin?system_id=sys-GAfNtUViWCw&state=true status=500 duration=529.36ms
Your field `extension_data` is declared as `JSON::Any` but `NULL` value has been found in the database. (Exception)
  from app/lib/clear/src/clear/model/column.cr:80:5 in 'reset'
  from app/lib/clear/src/clear/model/modules/has_saving.cr:113:15 in 'save'
  from app/src/controllers/events.cr:729:68 in 'guest_checkin'
  ```

**Comment by stakach** [comment]
@w-le could you re-test?
Should be resolved now

**Comment by w-le** [comment]
tested OK with a concierge checkin.

Note that VISITOR KIOSK frontend will attempt to GET the visitor and the visitor's meetings before it does a checkin (which obviously makes sense), so kiosk checkins still won't work. But I believe that's ok FOR NOW because all kiosks we have use QR code checkin and the QRs are only sent when the event was created using a placeos app (and in that scenario the Visitor object is created upon event creation).

So if there are any scenarios where a placeos kiosk allows a user to enter their email to checkin to an event that was created via Outlook then the visitor lookup will still 404. IF we want to care for that behaviour then we can do an additional PR.

FYI @pkheav

**Review by w-le — APPROVED** [review]
tested OK for CONCIERGE checkin only in dev env. This change functions as expected.

**Pull request merged**
