### PR TITLE
feat(guests controller): make email mutable

### LINKED ISSUE #95: Support nilable, mutable guest emails
**Is your feature request related to a problem? Please describe.**
Guest may not have (or wish to provide) an email address. This results in either fake, or placeholder addresses needing to be used. Similarly, there may be workflows where a guest must be created, before an email is known.

**Describe the solution you'd like**
Make the guest [`email` attribute](https://github.com/place-labs/staff-api/blob/8d85c302373ec3bf76bb7da53ce9b3ee6015e24f/src/models/guest.cr#L6) nilable, and add to the [mutatable fields](https://github.com/place-labs/staff-api/blob/50f64c157200a7725ab31bcb43e2a0bcc0562998/src/controllers/guests.cr#L167) on the guests endpoint.

**Additional context**
https://github.com/place-technology/suncorp-ntt/issues/46

### PR DESCRIPTION
**Pull request by stakach**
resolves #95
making it nilable is not really possible given the design.
The entry should be deleted or a dummy email assigned

### CODE REVIEW

**Comment by kimburgess** [comment]
Hmmmm, this may get messy. It looks like some of the approach to security here relies on these addresses being immutable: https://github.com/PlaceOS/staff-api/blob/9fc84a688da1a689657f68f33a3a8bea9b84abeb/src/controllers/guests.cr#L162

**Comment by kimburgess** [comment]
What's the lifetime on those auth tokens? IIRC there are use cases where these can be longer lived (in an email etc).

Could an alt approach be to keep a list of emails so history is preserved? An accessor would then return either the head/tail of this, or some form of symbolic value / a placeholder address if one is not known (empty list) solving the nilable use case. Auth checks can then also walk this so that previously issued token would remain valid if these are the only keys.

Would still need to take some care to ensure there isn't the ability to claim another guests email (and associated privs) though.

**Comment by stakach** [comment]
Yeah, those tokens last until the meeting the guest is invited to ends
This is why they were not mutable in the first place

We can protect the email field from modification by guests or only allow modification if there are no upcoming visits?
(which prevents edits by the guest themselves and ensures no broken data)

**Comment by jcit1** [comment]
Hi guys,

Yeah if a visitor rocked up and adjusted their email (after we find them with the incorrect email or their mobile) we were going to find the existing events (with old email) and re-add the new email automatically.  This would resend out the invite to the correct email with new JWT.  Would that not have worked?

**Comment by stakach** [comment]
yeah, that should work without this logic - so we can probably ignore this and close the issue?

**Pull request merged**
